# Generated by Django 5.2.17 on 2026-09-05.

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("schedule_type", models.CharField(choices=[("one_time", "One-time"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], max_length=10)),
                ("start_date", models.DateField()),
                ("due_time", models.TimeField(default=datetime.time(9, 0))),
                ("recurrence_weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("recurrence_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_chore_series", to="households.membership")),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chore_series", to="households.household")),
            ],
        ),
        migrations.CreateModel(
            name="ChoreOccurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("due_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("overdue", "Overdue")], default="pending", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_occurrences", to="households.membership")),
                ("series", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="occurrences", to="chores.choreseries")),
            ],
            options={"ordering": ["due_at"], "constraints": [models.UniqueConstraint(fields=("series", "due_at"), name="unique_series_due_at")]},
        ),
    ]
